# Generated by Django 5.1.15 on 2026-05-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("program", "Program"),
                            ("story", "Impact story"),
                            ("campaign", "Campaign"),
                            ("partner", "Partner"),
                            ("event", "Event"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("slug", models.SlugField(max_length=180)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("image", models.ImageField(blank=True, upload_to="content/")),
                ("external_image_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        db_index=True,
                        default="draft",
                        max_length=40,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["content_type", "sort_order", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("content_type", "slug"), name="unique_content_type_slug")
                ],
            },
        ),
    ]
