# Generated by Django 5.1.15 on 2026-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('collaboration_interest', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
