# Generated by Django 5.1.15 on 2026-05-20 15:53

import apps.donations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reference",
                    models.CharField(default=apps.donations.models.make_reference, max_length=80, unique=True),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("bank", "Bank transfer"),
                        ],
                        default="paystack",
                        max_length=40,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, db_index=True, max_length=120)),
                ("donor_name", models.CharField(blank=True, max_length=255)),
                ("donor_email", models.EmailField(max_length=254)),
                ("amount_minor", models.PositiveIntegerField()),
                ("currency", models.CharField(default="NGN", max_length=8)),
                ("campaign_slug", models.SlugField(default="community-care-fund", max_length=180)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("checkout_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status", "created_at"], name="donations_d_status_ad9788_idx")],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=40)),
                ("event_type", models.CharField(max_length=120)),
                ("event_id", models.CharField(blank=True, max_length=180)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="donations.donation"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["provider", "event_type"], name="donations_p_provide_167923_idx")],
            },
        ),
    ]
